/**
 * Knowledge base fact write gate — state mutation policy for jingu-trust-gate.
 *
 * Use case: a research agent proposes facts to write into a shared knowledge
 * base (wiki, structured DB, document store). Before any fact reaches storage,
 * the gate verifies that the fact is grounded in retrieved source material —
 * not generated by the LLM without evidence.
 *
 * This is the "state" gating pattern applied to knowledge base writes:
 * controlling what enters the shared knowledge store is more important than
 * controlling what appears in a single response, because unverified facts
 * persist and accumulate.
 *
 * Domain types
 *   FactWrite         — one proposed fact to store
 *   SourceEvidence    — shape of SupportRef.attributes for retrieved sources
 *
 * Gate rules (evaluateUnit)
 *   R1  no retrieved source evidence at all              → UNSOURCED            → reject
 *   R2  claim is more specific than source supports      → OVER_SPECIFIC        → downgrade to "derived"
 *   R3  source is flagged as low-confidence              → LOW_CONFIDENCE_SOURCE → downgrade to "uncertain"
 *   R4  everything else                                  → approve
 *
 * Key idea:
 *   Unlike RAG responses (where a hallucinated fact affects one reply), a
 *   hallucinated KB write contaminates every future query that retrieves it.
 *   The gate enforces source grounding at the storage boundary.
 *
 * Run:
 *   npm run build && node dist/examples/state/fact-write-policy.js
 */

import assert from "node:assert/strict";
import { createTrustGate } from "../../src/trust-gate.js";
import type { GatePolicy } from "../../src/types/policy.js";
import type { Proposal } from "../../src/types/proposal.js";
import type { SupportRef, UnitWithSupport } from "../../src/types/support.js";
import type {
  StructureValidationResult,
  UnitEvaluationResult,
  ConflictAnnotation,
} from "../../src/types/gate.js";
import type { AdmittedUnit } from "../../src/types/admission.js";
import type { VerifiedContext, RenderContext } from "../../src/types/renderer.js";
import type { RetryFeedback, RetryContext } from "../../src/types/retry.js";
import type { AuditEntry, AuditWriter } from "../../src/types/audit.js";
import { approve, reject, downgrade, firstFailing } from "../../src/helpers/index.js";

// ── Domain types ──────────────────────────────────────────────────────────────

type FactGrade = "verified" | "derived" | "uncertain";

type FactWrite = {
  id: string;
  subject: string;          // entity or topic the fact describes
  predicate: string;        // relationship or property
  value: string;            // the claim value
  grade: FactGrade;         // "verified" = in source verbatim; "derived" = inferred from source
  evidenceRefs: string[];   // sourceIds of retrieved sources that support this fact
};

// Shape of SupportRef.attributes for retrieved source material
type SourceEvidence = {
  sourceTitle: string;
  sourceUrl: string;
  excerpt: string;          // the specific passage that supports the fact
  confidence: "high" | "medium" | "low";
  retrievedAt: string;      // ISO timestamp
};

// ── Policy ────────────────────────────────────────────────────────────────────

class FactWritePolicy implements GatePolicy<FactWrite> {

  validateStructure(proposal: Proposal<FactWrite>): StructureValidationResult {
    const errors: StructureValidationResult["errors"] = [];

    if (proposal.units.length === 0) {
      errors.push({ field: "units", reasonCode: "EMPTY_PROPOSAL" });
      return { kind: "structure", valid: false, errors };
    }

    for (const unit of proposal.units) {
      if (!unit.id?.trim()) {
        errors.push({ field: "id", reasonCode: "MISSING_UNIT_ID" });
      }
      if (!unit.subject?.trim()) {
        errors.push({ field: "subject", reasonCode: "MISSING_SUBJECT", message: `unit ${unit.id}` });
      }
      if (!unit.predicate?.trim()) {
        errors.push({ field: "predicate", reasonCode: "MISSING_PREDICATE", message: `unit ${unit.id}` });
      }
      if (!Array.isArray(unit.evidenceRefs)) {
        errors.push({ field: "evidenceRefs", reasonCode: "MISSING_EVIDENCE_REFS", message: `unit ${unit.id}` });
      }
    }

    return { kind: "structure", valid: errors.length === 0, errors };
  }

  bindSupport(unit: FactWrite, pool: SupportRef[]): UnitWithSupport<FactWrite> {
    const matched = pool.filter(s => unit.evidenceRefs.includes(s.sourceId));
    return {
      unit,
      supportIds: matched.map(s => s.id),
      supportRefs: matched,
    };
  }

  evaluateUnit(
    uws: UnitWithSupport<FactWrite>,
    _ctx: { proposalId: string; proposalKind: string }
  ): UnitEvaluationResult {
    return firstFailing([
      this.#checkSource(uws),
      this.#checkLowConfidence(uws),
      this.#checkOverSpecific(uws),
    ]) ?? approve(uws.unit.id);
  }

  // R1: at least one retrieved source must be bound.
  // A fact with no sources is an LLM hallucination — never write it.
  #checkSource({ unit, supportRefs }: UnitWithSupport<FactWrite>) {
    if (supportRefs.length === 0) {
      return reject(unit.id, "UNSOURCED", {
        subject: unit.subject,
        predicate: unit.predicate,
        note: `Fact "${unit.subject} ${unit.predicate} ${unit.value}" has no retrieved source. ` +
              `Do not write unsourced facts into the knowledge base.`,
      });
    }
    return undefined;
  }

  // R3: if any bound source is low-confidence, downgrade to "uncertain".
  // Low-confidence sources can support tentative writes, but the KB must track that.
  #checkLowConfidence({ unit, supportRefs }: UnitWithSupport<FactWrite>) {
    const lowConfSource = supportRefs.find(s => {
      const attrs = s.attributes as SourceEvidence | undefined;
      return attrs?.confidence === "low";
    });
    if (lowConfSource) {
      const attrs = lowConfSource.attributes as SourceEvidence;
      return downgrade(unit.id, "LOW_CONFIDENCE_SOURCE", "uncertain", {
        sourceTitle: attrs.sourceTitle,
        note: `Source "${attrs.sourceTitle}" is marked low-confidence. ` +
              `Downgraded to grade="uncertain" — KB should tag for re-verification.`,
      });
    }
    return undefined;
  }

  // R2: grade=verified but the value is more specific than any source excerpt contains.
  // Heuristic: value must appear (case-insensitive) in at least one excerpt.
  #checkOverSpecific({ unit, supportRefs }: UnitWithSupport<FactWrite>) {
    if (unit.grade === "verified") {
      const appearsInExcerpt = supportRefs.some(s => {
        const attrs = s.attributes as SourceEvidence | undefined;
        return attrs?.excerpt.toLowerCase().includes(unit.value.toLowerCase());
      });
      if (!appearsInExcerpt) {
        return downgrade(unit.id, "OVER_SPECIFIC", "derived", {
          value: unit.value,
          note: `Value "${unit.value}" does not appear verbatim in any source excerpt. ` +
                `Downgraded to grade="derived" — the fact was synthesized, not directly sourced.`,
        });
      }
    }
    return undefined;
  }

  detectConflicts(
    units: UnitWithSupport<FactWrite>[],
    _pool: SupportRef[]
  ): ConflictAnnotation[] {
    // Detect conflicting values for the same subject+predicate pair.
    const conflicts: ConflictAnnotation[] = [];
    const seen = new Map<string, UnitWithSupport<FactWrite>>();

    for (const uws of units) {
      const key = `${uws.unit.subject}::${uws.unit.predicate}`;
      const prior = seen.get(key);
      if (prior && prior.unit.value !== uws.unit.value) {
        conflicts.push({
          unitIds: [prior.unit.id, uws.unit.id],
          conflictCode: "CONFLICTING_VALUES",
          sources: [...prior.supportIds, ...uws.supportIds],
          severity: "informational",
          description:
            `Two facts assert different values for "${uws.unit.subject} ${uws.unit.predicate}": ` +
            `"${prior.unit.value}" vs "${uws.unit.value}". Both admitted with conflict note.`,
        });
      } else {
        seen.set(key, uws);
      }
    }

    return conflicts;
  }

  render(
    admittedUnits: AdmittedUnit<FactWrite>[],
    _pool: SupportRef[],
    _ctx: RenderContext
  ): VerifiedContext {
    const admittedBlocks = admittedUnits.map(u => {
      const fact = u.unit as FactWrite;
      const currentGrade = u.appliedGrades[u.appliedGrades.length - 1] ?? fact.grade;
      const conflict = u.conflictAnnotations?.[0];
      return {
        sourceId: u.unitId,
        content: `${fact.subject} | ${fact.predicate} | ${fact.value}`,
        grade: currentGrade,
        ...(u.status === "downgraded" && {
          unsupportedAttributes: [u.evaluationResults[0]?.reasonCode ?? ""],
        }),
        ...(conflict && {
          conflictNote: conflict.description,
        }),
      };
    });

    return {
      admittedBlocks,
      summary: {
        admitted: admittedUnits.length,
        rejected: 0,
        conflicts: admittedUnits.filter(u => u.status === "approved_with_conflict").length,
      },
      instructions:
        "Write only the verified facts below to the knowledge base. " +
        "grade=\"derived\" facts should be stored with a note that the value was synthesized from sources. " +
        "grade=\"uncertain\" facts should be tagged for human re-verification before being treated as authoritative. " +
        "Facts with conflict notes should be reviewed before replacing existing KB entries.",
    };
  }

  buildRetryFeedback(
    unitResults: UnitEvaluationResult[],
    ctx: RetryContext
  ): RetryFeedback {
    const failed = unitResults.filter(r => r.decision === "reject");
    return {
      summary:
        `${failed.length} fact write(s) rejected on attempt ${ctx.attempt}/${ctx.maxRetries}. ` +
        `Every fact must be grounded in retrieved source material.`,
      errors: failed.map(r => ({
        unitId: r.unitId,
        reasonCode: r.reasonCode,
        details: {
          hint: r.reasonCode === "UNSOURCED"
            ? "Retrieve a source document and add its sourceId to evidenceRefs before proposing this fact"
            : "Review gate policy requirements",
        },
      })),
    };
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function noopAuditWriter(): AuditWriter {
  return { append: async (_e: AuditEntry) => {} };
}

function pass(msg: string): void {
  console.log(`    [PASS] ${msg}`);
}

function sep(title: string): void {
  console.log("\n" + "═".repeat(70));
  console.log(`  ${title}`);
  console.log("═".repeat(70));
}

function subsep(title: string): void {
  console.log(`\n  ── ${title}`);
}

function label(key: string, value: unknown): void {
  console.log(`    ${key.padEnd(32)}: ${JSON.stringify(value)}`);
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const gate = createTrustGate({
    policy: new FactWritePolicy(),
    auditWriter: noopAuditWriter(),
  });

  // ── Scenario A: Research agent proposes 4 KB facts ──────────────────────────
  //
  // Retrieved sources: two papers on climate topics.
  // Proposed facts:
  //   - fact-1: CO2 level (exact figure in source)          → APPROVE
  //   - fact-2: temperature rise (over-specific inference)   → DOWNGRADE (OVER_SPECIFIC)
  //   - fact-3: sea level rise by 2100 (low-conf source)     → DOWNGRADE (LOW_CONFIDENCE_SOURCE)
  //   - fact-4: arctic ice melt year (no source at all)      → REJECT (UNSOURCED)

  sep("Scenario A — Research agent proposes 4 KB facts");
  subsep("INPUT: retrieved source pool");

  const poolA: SupportRef[] = [
    {
      id: "ref-src-1",
      sourceId: "ipcc-ar6-ch2",
      sourceType: "observation",
      attributes: {
        sourceTitle: "IPCC AR6 Chapter 2 — Changing State of the Climate System",
        sourceUrl: "https://example.com/ipcc-ar6-ch2",
        excerpt: "Atmospheric CO2 concentration reached 410 ppm in 2019, the highest level in at least 2 million years.",
        confidence: "high",
        retrievedAt: "2024-01-15T10:00:00Z",
      } satisfies SourceEvidence,
    },
    {
      id: "ref-src-2",
      sourceId: "nature-climate-proj",
      sourceType: "observation",
      attributes: {
        sourceTitle: "Nature Climate Change — 2050 Temperature Projections",
        sourceUrl: "https://example.com/nature-climate-proj",
        excerpt: "Under RCP 8.5, global mean surface temperature is projected to rise by 1.5–4.5°C by 2100 relative to 1850–1900.",
        confidence: "medium",
        retrievedAt: "2024-01-15T10:05:00Z",
      } satisfies SourceEvidence,
    },
    {
      id: "ref-src-3",
      sourceId: "blog-climate-2023",
      sourceType: "observation",
      attributes: {
        sourceTitle: "Climate Blog Post — 2023 Projections",
        sourceUrl: "https://example.com/blog-climate-2023",
        excerpt: "Sea levels could rise between 0.3 and 1.0 meters by 2100 according to various models.",
        confidence: "low",     // blog post, not peer-reviewed
        retrievedAt: "2024-01-15T10:10:00Z",
      } satisfies SourceEvidence,
    },
  ];

  console.log("\n  Retrieved sources:");
  for (const ref of poolA) {
    const attrs = ref.attributes as SourceEvidence;
    label(`  ${ref.sourceId} [conf=${attrs.confidence}]`, attrs.sourceTitle);
    label("    excerpt", attrs.excerpt.slice(0, 80) + "…");
  }

  const proposalA: Proposal<FactWrite> = {
    id: "prop-kb-001",
    kind: "response",
    units: [
      // fact-1: CO2 level — appears verbatim in ipcc-ar6-ch2 → APPROVE
      {
        id: "fact-1",
        subject: "atmosphere",
        predicate: "CO2_concentration_2019_ppm",
        value: "410",
        grade: "verified",
        evidenceRefs: ["ipcc-ar6-ch2"],
      },
      // fact-2: temperature rise — source says "1.5–4.5°C", agent proposes "3.2°C" (specific, not in source) → DOWNGRADE
      {
        id: "fact-2",
        subject: "global_mean_surface_temperature",
        predicate: "projected_rise_by_2100_celsius",
        value: "3.2",   // "3.2" does not appear in the excerpt
        grade: "verified",
        evidenceRefs: ["nature-climate-proj"],
      },
      // fact-3: sea level rise — source is low-confidence blog → DOWNGRADE (LOW_CONFIDENCE_SOURCE)
      {
        id: "fact-3",
        subject: "sea_level",
        predicate: "projected_rise_by_2100_meters",
        value: "0.3-1.0",
        grade: "verified",
        evidenceRefs: ["blog-climate-2023"],
      },
      // fact-4: arctic ice — no source in pool at all → REJECT (UNSOURCED)
      {
        id: "fact-4",
        subject: "arctic_sea_ice",
        predicate: "summer_free_year",
        value: "2050",
        grade: "verified",
        evidenceRefs: [],   // LLM hallucinated this — no source
      },
    ],
  };

  subsep("GATE EXECUTION");

  const resultA = await gate.admit(proposalA, poolA);
  const contextA = gate.render(resultA, poolA);
  const explA = gate.explain(resultA);

  subsep("OUTPUT: gate results");

  console.log("\n  Admitted facts:");
  for (const u of resultA.admittedUnits) {
    const fact = u.unit as FactWrite;
    const grade = u.appliedGrades.at(-1) ?? fact.grade;
    label(`  ${u.unitId} [${u.status}, grade=${grade}]`, `${fact.subject} ${fact.predicate} = ${fact.value}`);
    if (u.status === "downgraded") {
      const ann = u.evaluationResults[0]?.annotations as any;
      if (ann?.note) label("    note", ann.note);
    }
  }

  console.log("\n  Rejected facts:");
  for (const u of resultA.rejectedUnits) {
    const fact = u.unit as FactWrite;
    label(`  ${u.unitId} [${u.evaluationResults[0]?.reasonCode}]`, `${fact.subject} ${fact.predicate} = ${fact.value}`);
    const ann = u.evaluationResults[0]?.annotations as any;
    if (ann?.note) label("    note", ann.note);
  }

  console.log();
  label("approved", explA.approved);
  label("downgraded", explA.downgraded);
  label("rejected", explA.rejected);

  console.log("\n  Verified KB writes:");
  for (const block of contextA.admittedBlocks) {
    label(`  ${block.sourceId} [${block.grade}]`, block.content);
  }

  subsep("ASSERTIONS");

  const f1 = resultA.admittedUnits.find(u => u.unitId === "fact-1");
  assert.ok(f1);
  assert.equal(f1.status, "approved");
  pass("fact-1 (CO2=410ppm) approved — exact value appears in IPCC source excerpt");

  const f2 = resultA.admittedUnits.find(u => u.unitId === "fact-2");
  assert.ok(f2);
  assert.equal(f2.status, "downgraded");
  assert.equal(f2.appliedGrades.at(-1), "derived");
  assert.equal(f2.evaluationResults[0]?.reasonCode, "OVER_SPECIFIC");
  pass("fact-2 (temp=3.2°C) downgraded to derived (OVER_SPECIFIC — source says 1.5–4.5°C range)");

  const f3 = resultA.admittedUnits.find(u => u.unitId === "fact-3");
  assert.ok(f3);
  assert.equal(f3.status, "downgraded");
  assert.equal(f3.appliedGrades.at(-1), "uncertain");
  assert.equal(f3.evaluationResults[0]?.reasonCode, "LOW_CONFIDENCE_SOURCE");
  pass("fact-3 (sea level) downgraded to uncertain (LOW_CONFIDENCE_SOURCE — blog post)");

  const f4 = resultA.rejectedUnits.find(u => u.unitId === "fact-4");
  assert.ok(f4);
  assert.equal(f4.evaluationResults[0]?.reasonCode, "UNSOURCED");
  pass("fact-4 (arctic ice) rejected (UNSOURCED — no retrieved source evidence)");

  assert.equal(explA.approved, 1);
  assert.equal(explA.downgraded, 2);
  assert.equal(explA.rejected, 1);
  pass("summary: 1 approved, 2 downgraded, 1 rejected");

  // ── Scenario B: Conflicting facts for the same subject+predicate ─────────────
  //
  // Two sources give different values for the same fact.
  // Both are admitted (informational conflict), both flagged with conflict note.

  sep("Scenario B — Conflicting facts for the same KB entry");

  const poolB: SupportRef[] = [
    {
      id: "ref-src-4",
      sourceId: "source-a",
      sourceType: "observation",
      attributes: {
        sourceTitle: "Source A",
        sourceUrl: "https://example.com/a",
        excerpt: "The global average temperature anomaly in 2023 was +1.45°C above pre-industrial levels.",
        confidence: "high",
        retrievedAt: "2024-01-15T11:00:00Z",
      } satisfies SourceEvidence,
    },
    {
      id: "ref-src-5",
      sourceId: "source-b",
      sourceType: "observation",
      attributes: {
        sourceTitle: "Source B",
        sourceUrl: "https://example.com/b",
        excerpt: "2023 recorded a temperature anomaly of +1.48°C relative to the 1850–1900 baseline.",
        confidence: "high",
        retrievedAt: "2024-01-15T11:05:00Z",
      } satisfies SourceEvidence,
    },
  ];

  const proposalB: Proposal<FactWrite> = {
    id: "prop-kb-002",
    kind: "response",
    units: [
      {
        id: "fact-5",
        subject: "global_temperature_anomaly_2023",
        predicate: "degrees_celsius_above_preindustrial",
        value: "1.45",
        grade: "verified",
        evidenceRefs: ["source-a"],
      },
      {
        id: "fact-6",
        subject: "global_temperature_anomaly_2023",
        predicate: "degrees_celsius_above_preindustrial",
        value: "1.48",
        grade: "verified",
        evidenceRefs: ["source-b"],
      },
    ],
  };

  const resultB = await gate.admit(proposalB, poolB);
  const explB = gate.explain(resultB);

  subsep("OUTPUT: conflict results");

  for (const u of resultB.admittedUnits) {
    const fact = u.unit as FactWrite;
    label(`  ${u.unitId} [${u.status}]`, `${fact.predicate} = ${fact.value}`);
    if (u.conflictAnnotations?.length) {
      label("    conflict", u.conflictAnnotations[0]?.conflictCode);
    }
  }
  label("conflicts", explB.conflicts);
  label("admitted", explB.approved + explB.downgraded + explB.conflicts);

  subsep("ASSERTIONS");

  assert.ok(resultB.hasConflicts, "should have conflicts");
  assert.equal(resultB.admittedUnits.length, 2, "both facts admitted (informational conflict)");
  pass("both fact-5 and fact-6 admitted with CONFLICTING_VALUES conflict note");
  pass("informational conflict — KB writer should review before updating authoritative entry");

  console.log("\n  Done.\n");
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
